version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: exchange-service:latest
    environment:
      AUTH_URL: http://localhost:9003/validate
      STORE_FUND_URL: http://localhost:9001/
      GET_WALLET_URL: http://localhost:9001/address/
    ports:
      - "9002:80"
