amazon:
  access:
    key: AKIAXQKJ7DSHMEBBZJVS
    secret-key: 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
  region: ap-south-1
  end-point:
    url: dynamodb.ap-south-1.amazonaws.com
server:
  port: 9002

auth-url: http://localhost:9003/validate
store-fund-url: http://localhost:9001/wallets/
get-wallet-url: http://localhost:9001/wallets/address/